<a href="https://colab.research.google.com/github/NattInsights/ds/blob/main/tennis_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [2]:
from google.colab import files
uploaded = files.upload()

Saving atp_tennis.csv to atp_tennis.csv

In [4]:
df = pd.read_csv('atp_tennis.csv', sep=',')

In [7]:
df.head()

,Tournament,Date,Series,Court,Surface,Round,Best of,Player_1,Player_2,Winner,Rank_1,Rank_2,Pts_1,Pts_2,Odd_1,Odd_2,Score
0,Australian Hardcourt Championships,2000-01-03,International,Outdoor,Hard,1st Round,3,Arthurs W.,Gambill J.M.,Gambill J.M.,105,58,-1,-1,-1.0,-1.0,6-3 6-7 4-6
1,Australian Hardcourt Championships,2000-01-03,International,Outdoor,Hard,1st Round,3,Balcells J.,Henman T.,Henman T.,218,11,-1,-1,-1.0,-1.0,4-6 6-7
2,Australian Hardcourt Championships,2000-01-03,International,Outdoor,Hard,1st Round,3,Clement A.,Enqvist T.,Enqvist T.,56,5,-1,-1,-1.0,-1.0,3-6 3-6
3,Australian Hardcourt Championships,2000-01-03,International,Outdoor,Hard,1st Round,3,Dosedel S.,Ljubicic I.,Dosedel S.,63,77,-1,-1,-1.0,-1.0,6-4 6-2
4,Australian Hardcourt Championships,2000-01-03,International,Outdoor,Hard,1st Round,3,Draper S.,Norman M.,Norman M.,155,15,-1,-1,-1.0,-1.0,4-6 4-6

In [27]:
df.describe()

,Best of,Rank_1,Rank_2,Pts_1,Pts_2,Odd_1,Odd_2
count,68635.000000,68635.000000,68635.000000,68635.000000,68635.000000,68635.000000,68635.000000
mean,3.377213,75.863087,75.422452,1144.517841,1151.747010,2.422493,2.414463
std,0.782397,100.242693,100.652846,1728.297181,1747.850943,2.677432,2.639093
min,3.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000
25%,3.000000,25.000000,24.000000,159.000000,161.000000,1.360000,1.353292
50%,3.000000,54.000000,54.000000,709.000000,710.000000,1.773750,1.800000
75%,3.000000,92.000000,92.000000,1258.000000,1265.000000,2.750000,2.750000
max,5.000000,3390.000000,4915.000000,16950.000000,16950.000000,67.000000,51.000000

In [24]:
df.loc[[5,100,6000,60000], ['Pts_1', 'Pts_2', 'Odd_1', 'Odd_2']]

       Pts_1  Pts_2    Odd_1   Odd_2
5         -1     -1 -1.00000 -1.0000
100       -1     -1 -1.00000 -1.0000
6000      -1     -1  1.53025  2.2625
60000    779    767  1.62000  2.3000

In [ ]:
tennis.set_index('Date')

,Tournament,Series,Court,Surface,Round,Best of,Player_1,Player_2,Winner,Rank_1,Rank_2,Pts_1,Pts_2,Odd_1,Odd_2,Score
Date,,,,,,,,,,,,,,,,
2000-01-03,Australian Hardcourt Championships,International,Outdoor,Hard,1st Round,3,Arthurs W.,Gambill J.M.,Gambill J.M.,105,58,-1,-1,-1.00,-1.00,6-3 6-7 4-6
2000-01-03,Australian Hardcourt Championships,International,Outdoor,Hard,1st Round,3,Balcells J.,Henman T.,Henman T.,218,11,-1,-1,-1.00,-1.00,4-6 6-7
2000-01-03,Australian Hardcourt Championships,International,Outdoor,Hard,1st Round,3,Clement A.,Enqvist T.,Enqvist T.,56,5,-1,-1,-1.00,-1.00,3-6 3-6
2000-01-03,Australian Hardcourt Championships,International,Outdoor,Hard,1st Round,3,Dosedel S.,Ljubicic I.,Dosedel S.,63,77,-1,-1,-1.00,-1.00,6-4 6-2
2000-01-03,Australian Hardcourt Championships,International,Outdoor,Hard,1st Round,3,Draper S.,Norman M.,Norman M.,155,15,-1,-1,-1.00,-1.00,4-6 4-6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2026-08-27,Winston-Salem Open at Wake Forest University,ATP250,Outdoor,Hard,Quarterfinals,3,Van De Zandschulp B.,Bonzi B.,Bonzi B.,71,109,834,572,1.44,2.75,6-7 4-6
2026-08-28,Winston-Salem Open at Wake Forest University,ATP250,Outdoor,Hard,Quarterfinals,3,Duckworth J.,Marozsan F.,Duckworth J.,79,63,763,930,2.38,1.57,6-7 6-2 6-4
2026-08-28,Winston-Salem Open at Wake Forest University,ATP250,Outdoor,Hard,Quarterfinals,3,Kovacevic A.,Fery A.,Fery A.,89,37,690,1253,1.91,1.91,6-3 5-7 3-6
2026-08-28,Winston-Salem Open at Wake Forest University,ATP250,Outdoor,Hard,Semifinals,3,Bonzi B.,Buse I.,Buse I.,109,36,572,1310,1.73,2.10,2-6 6-4 1-6
2026-08-29,Winston-Salem Open at Wake Forest University,ATP250,Outdoor,Hard,The Final,3,Buse I.,Fery A.,Buse I.,36,37,1310,1253,2.10,1.73,6-3 6-2

In [ ]:
# conditional selection
#tennis.loc[tennis.Winner == "Draper S."]
tennis.loc[(tennis.Winner == "Draper S.") & (tennis.Series == "International")]

,Tournament,Date,Series,Court,Surface,Round,Best of,Player_1,Player_2,Winner,Rank_1,Rank_2,Pts_1,Pts_2,Odd_1,Odd_2,Score
0,Australian Hardcourt Championships,2000-01-03,International,Outdoor,Hard,1st Round,3,Arthurs W.,Gambill J.M.,Draper S.,105,58,-1,-1,-1.00,-1.00,6-3 6-7 4-6
1,Australian Hardcourt Championships,2000-01-03,International,Outdoor,Hard,1st Round,3,Balcells J.,Henman T.,Draper S.,218,11,-1,-1,-1.00,-1.00,4-6 6-7
2,Australian Hardcourt Championships,2000-01-03,International,Outdoor,Hard,1st Round,3,Clement A.,Enqvist T.,Draper S.,56,5,-1,-1,-1.00,-1.00,3-6 3-6
3,Australian Hardcourt Championships,2000-01-03,International,Outdoor,Hard,1st Round,3,Dosedel S.,Ljubicic I.,Draper S.,63,77,-1,-1,-1.00,-1.00,6-4 6-2
4,Australian Hardcourt Championships,2000-01-03,International,Outdoor,Hard,1st Round,3,Draper S.,Norman M.,Draper S.,155,15,-1,-1,-1.00,-1.00,4-6 4-6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24855,St. Petersburg Open,2008-10-25,International,Indoor,Carpet,Semifinals,3,Hanescu V.,Golubev A.,Draper S.,66,150,629,290,1.40,2.75,3-6 0-6
24856,St. Petersburg Open,2008-10-25,International,Indoor,Carpet,Semifinals,3,Murray A.,Verdasco F.,Draper S.,4,16,3420,1410,1.16,4.50,6-0 6-3
24859,Davidoff Swiss Indoors,2008-10-26,International,Indoor,Carpet,The Final,5,Federer R.,Nalbandian D.,Draper S.,2,8,5805,1750,1.28,3.75,6-3 6-4
24860,Grand Prix de Lyon,2008-10-26,International,Indoor,Carpet,The Final,3,Benneteau J.,Soderling R.,Draper S.,56,27,704,1115,2.75,1.44,3-6 7-6 1-6
24861,St. Petersburg Open,2008-10-26,International,Indoor,Carpet,The Final,3,Golubev A.,Murray A.,Draper S.,150,4,290,3420,10.00,1.05,1-6 1-6